config/routes.rb
Rails.application.routes.draw do
  root "candidates#index"
  resources :candidates do 
    member do
      post :vote
    end 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord

validates :name, :party, :age, :policy, presence: true
has_many :vote_logs
scope :young_people, -> {where('age<40')}
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]
    def index
        @candidates = Candidate.all
        @candidate = Candidate.young_people
    end

    def new
        @candidate = Candidate.new
    end

    def show
       
    end
    
    def create

       @candidate = Candidate.new(candidate_params)

       if @candidate.save
        redirect_to '/candidates', notice: 'Candidate Created!'
       else
        render :new
       end
    end

    def edit
       
    end 
    
    def update
       

        if @candidate.update(candidate_params)    
            redirect_to '/candidates', notice: 'Candidate Updated'
        else
            render :edit
        end    
    end
    
    def destroy
        
        @candidate.destroy
        redirect_to '/candidates', notice: 'Candidate Deleted'
    end    

    def vote
        

        # VoteLog.create(candidate: @candidate, ip_address: request.remote_ip) （另一種寫法）

        @candidate.vote_logs.create(ip_address: request.remote_ip)
        redirect_to '/candidates', notice: 'Successfully voted'
    end 

    private
    def candidate_params
        params.require(:candidate).permit(:name, :party, :age, :policy)
    end

    def find_candidate
        @candidate = Candidate.find_by(id: params[:id])
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
    <ul>
        <% candidate.errors.full_messages.each do 
            |messages| %>
            <li><%= messages %></li>
        <% end %>
    </ul>
<% end %>


<%= form_for (candidate) do |form| %>

<div> 
    <%= form.text_field:name %>
    <%= form.label :name %>
</div>

<div> 
    <%= form.text_field :party %>
    <%= form.label :party %>
</div>


<div>
    <%= form.text_field :age %>
    <%= form.label :age %>
</div>   


<div>
    <%= form.text_area :policy %>
    <%= form.label :policy %>
</div>

<%= form.submit %>


<% end %>    

app/views/candidates/edit.html.erb
<h1> Edit Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<%= link_to 'Add Candidate' , new_candidate_path %>


<table>
<tr>
    
    <td>Votes</td>
    <td>Count</td>
    <td>Name </td>
    <td>Party </td>
    <td>Age </td>
    <td>Policy </td>
    <td>Action </td>

</tr>



<% @candidates.each do |candidate| %>

<tr>
    <td><%= link_to 'Vote' , vote_candidate_path(candidate.id), method: 'Post' %> </td>
    <td><%= candidate.vote_logs.size%> </td>
    <td><%= link_to candidate.name, candidate_path(candidate.id) %>  </td>
    <td><%=  candidate.party%> </td>
    <td><%=  candidate.age%> </td>
    <td><%=  candidate.policy%> </td>
    <td>
    <%= link_to 'update', edit_candidate_path(candidate.id) %> 

    <%= link_to 'delete', candidate_path(candidate.id), method: 'delete', data: {confirm: '你確定？'}  %>
    </td>

</tr>
<% end %>

</table>


      

app/views/candidates/new.html.erb
<h2> Add candidates </h2>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate %>

    <h1> <%= @candidate.name %> </h1>

    <ul>
        <li>party <%= @candidate.party %> </li>
        <li>age <%= @candidate.age %> </li>
        <li>policy <%= @candidate.policy %></li>
        
    </ul>

<% else %>
<h1>No Record Found! </h1>

<% end %>

<div> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>